docker-compose.yaml
version: '3.8'

services:
  jenkins:
    build: .
    container_name: unity-jenkins
    ports:
      - "9090:8080"
    volumes:
      - jenkins-data:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock

volumes:
  jenkins-data:
